# Generated by Django 5.1.4 on 2025-01-14 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
